--create database OOP_COURSEWORK

--CREATE TABLE AUTH
--(
--ID INT PRIMARY KEY,
--LOGIN VARCHAR(30),
--PASSWORD VARCHAR(30)
--)


--CREATE TABLE WALLET
--(
--IDWALLET INT PRIMARY KEY,
--BALANCE DECIMAL(17,3),
--HASH VARCHAR(40)
--)

--GO

	--CREATE TABLE PERSON
	--(
	--ID INT FOREIGN KEY REFERENCES AUTH(ID) primary key,
	--NAME VARCHAR(15),
	--SURNAME VARCHAR(20),
	--ROLE VARCHAR(20) CHECK (ROLE = 'Администратор' or ROLE = 'Модератор' or ROLE = 'Пользователь' ),
	--PICTURE VARCHAR(40),
	--IDWALLET INT FOREIGN KEY REFERENCES WALLET(IDWALLET)
	--)



USE OOP_COURSEWORK;

--create table HABBIT
--(
--	ID INT FOREIGN KEY REFERENCES PERSON(ID),
--	Title varchar(40),
--	Description varchar(100),
--	CreateDate date,
--	CurrentStreak int
--)


go