----create database OOP_COURSEWORK
use OOP_COURSEWORK
	drop table AUTH
	drop table PERSON
	drop table HABBIT
	drop table CHALLENGE
	drop table EVENT
	drop table WALLET

select * from Auth
select * from person
TABLE CREATE AUTH
(
ID INT PRIMARY KEY ,
LOGIN VARCHAR(255) unique,
PASSWORD VARCHAR(255),
SALT VARCHAR(255)
)
--USE OOP_COURSEWORK





--drop table WALLET

----GO
----ТУТ ПОМЕНЯЛ ФАМИЛИЮ 
CREATE TABLE WALLET
(
IDWALLET INT PRIMARY KEY,
BALANCE DECIMAL(17,3),
HASH VARCHAR(40)
)

CREATE TABLE PERSON
(
ID INT FOREIGN KEY REFERENCES AUTH(ID),
NAME VARCHAR(15),
LASTNAME VARCHAR(20),
ROLE VARCHAR(20) CHECK (ROLE = 'Администратор' or ROLE = 'Модератор' or ROLE = 'Пользователь' ),
PICTURE VARCHAR(40),
IDWALLET INT foreign key references Wallet(idwallet)
Primary key (id)
)


--drop table PERSON


select * from AUTH
select * from PERSON
--USE OOP_COURSEWORK;

create table HABBIT
(
	ID INT FOREIGN KEY REFERENCES PERSON(ID),
	Title varchar(40),
	Description varchar(100),
	DaysCount int,
	CreateDate date,
	CurrentStreak int
)



--SELECT * FROM PERSON

create table CHALLENGE
(
	CHALLENGEID INT PRIMARY KEY,
	CREATORID INT FOREIGN KEY REFERENCES PERSON(ID),
	TITLE VARCHAR(40),
	TIP VARCHAR(100),
	DAYSCOUNT INT,
	CHALLENGERID INT,
	EVENTID int unique
)

drop table CHALLENGE
CREATE TABLE EVENT
(
	EVENTID INT PRIMARY KEY FOREIGN KEY REFERENCES CHALLENGE(EVENTID),
	DAY VARCHAR(25),
	EVENT VARCHAR(50)
)

--go