----create database OOP_COURSEWORK
use OOP_COURSEWORK
drop table AUTH
drop table PERSON
drop table HABBIT
drop table CHALLENGE
drop table EVENT
drop table WALLET

CREATE TABLE AUTH
(
ID INT PRIMARY KEY identity(1,1),
LOGIN VARCHAR(255) unique,
PASSWORD VARCHAR(255),
SALT VARCHAR(255)
)
--USE OOP_COURSEWORK





--drop table WALLET

----GO
----ТУТ ПОМЕНЯЛ ФАМИЛИЮ 
CREATE TABLE PERSON
(
ID INT FOREIGN KEY REFERENCES AUTH(ID) identity(1,1),
NAME VARCHAR(15),
LASTNAME VARCHAR(20),
ROLE VARCHAR(20) CHECK (ROLE = 'Администратор' or ROLE = 'Модератор' or ROLE = 'Пользователь' ),
PICTURE VARCHAR(40),
IDWALLET INT foreign key references Wallet(idwallet)
Primary key (id)
)

CREATE TABLE WALLET
(
IDWALLET INT PRIMARY KEY,
BALANCE DECIMAL(17,3),
HASH VARCHAR(40)
)

--drop table PERSON



--USE OOP_COURSEWORK;

create table HABBIT
(
	ID INT FOREIGN KEY REFERENCES PERSON(ID),
	Title varchar(40),
	Description varchar(100),
	DaysCount int,
	CreateDate date,
	CurrentStreak int
)


CREATE TABLE EVENT
(
	EVENTID INT PRIMARY KEY FOREIGN KEY REFERENCES CHALLENGE(EVENTID),
	DAY VARCHAR(25),
	EVENT VARCHAR(50)
)

--SELECT * FROM PERSON

--create table CHALLENGE
--(
--	CHALLENGEID INT PRIMARY KEY,
--	CREATORID INT FOREIGN KEY REFERENCES PERSON(ID),
--	TITLE VARCHAR(40),
--	TIP VARCHAR(100),
--	DAYSCOUNT INT,
--	CHALLENGERID INT,
--	EVENTID int unique identity(1,1)
--)

--go