create procedure INSERTCHALLENGE 
@CHALLENGEID INT, @CREATORID INT, @TITTLE VARCHAR(40), @TIP VARCHAR(100), @DAYSCOUNT INT,
@CHALLENGERID INT, @EVENTID INT

AS INSERT INTO CHALLENGE(CHALLANGEID,CREATORID,TITLE,TIP,DAYSCOUNT,CHALLENGERID,EVENTID)
VALUES (@CHALLENGEID, @CREATORID, @TITTLE, @TIP, @DAYSCOUNT, @CHALLENGERID, @EVENTID)
SELECT * FROM CHALLENGE

EXEC INSERTCHALLENGE 