create procedure INSERTCHALLENGE 
@CHALLENGEID INT, @CREATORID INT, @TITTLE VARCHAR(40), @TIP VARCHAR(100), @DAYSCOUNT INT,
@Challenge INT, @EVENTID INT

AS INSERT INTO CHALLENGE(CHALLANGEID,CREATORID,TITLE,TIP,DAYSCOUNT,Challenge,EVENTID)
VALUES (@CHALLENGEID, @CREATORID, @TITTLE, @TIP, @DAYSCOUNT, @Challenge, @EVENTID)
SELECT * FROM CHALLENGE

EXEC INSERTCHALLENGE 

select * from AUTH